CREATE TABLE IF NOT EXISTS courses {
  crn INT(11) PRIMARY KEY,
  prefix VARCHAR(4) NOT NULL,
  num SMALLINT(4) NOT NULL,
  title VARCHAR(255) NOT NULL
};

ALTER TABLE courses
  ADD COLUMN section INT(2),
  ADD COLUMN yyyy INT(4);
