CREATE TABLE IF NOT EXISTS STUDENTS (
  RIN INT(9) PRIMARY KEY,
  RCSID CHAR(7),
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  ALIAS VARCHAR(100) NOT NULL,
  PHONE VARCHAR(10)
);

ALTER TABLE STUDENTS 
ADD COLUMN STREET VARCHAR(255),
ADD COLUMN CITY VARCHAR(100),
ADD COLUMN STATEABBR VARCHAR(2),
ADD COLUMN ZIP INT(5);


