CREATE TABLE IF NOT EXISTS STUDENTS (
  RIN INT(9) PRIMARY KEY,
  RCSID CHAR(7),
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  ALIAS VARCHAR(100) NOT NULL,
  PHONE VARCHAR(10)
);