CREATE TABLE LISTINGS (
  RCS_ID VARCHAR(10) NOT NULL, --Listing owner
  ACTIVE BOOLEAN NOT NULL,
  COLOR VARCHAR (30) NOT NULL,
  CONDITION VARCHAR(12) NOT NULL,
  CLICKS INT UNSIGNED NOT NULL,
  ITEM_DESCRIPTION VARCHAR(5000) NOT NULL, --FIGURE OUT WHY SIZE IS LIMITING ME
  LISTING_TITLE VARCHAR(100) NOT NULL,
  POSTING_DATE DATE NOT NULL,
  PRICE FLOAT NOT NULL
);
