CREATE TABLE LISTINGS (
  RCS_ID VARCHAR(10), --Listing owner
  ACTIVE BOOLEAN,
  COLOR VARCHAR (30),
  CONDITION VARCHAR(12),
  CLICKS INT,
  ITEM_DESCRIPTION VARCHAR(5000), --FIGURE OUT WHY SIZE IS LIMITING ME
  LISTING_TITLE VARCHAR(100),
  POSTING_DATE DATE,
  PRICE FLOAT
);
