CREATE TABLE USERS (
  RCS_ID VARCHAR(10) NOT NULL,
  ACTIVE_LISTINGS VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  PAST_LISTINGS VARCHAR(255) NOT NULL, 
  USER_PASSWORD VARCHAR(8) NOT NULL,
  USER_LOCATION VARCHAR(30) NOT NULL
);