CREATE TABLE USERS (
  RPI_ID VARCHAR(10), --User
  ACTIVE_LISTINGS VARCHAR(5000), --FIGURE OUT WHY SIZE IS LIMITING ME
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(30),
  PAST_LISTINGS VARCHAR(5000), --FIGURE OUT WHY SIZE IS LIMITING ME
  USER_PASSWORD VARCHAR(8),
  USER_LOCATION VARCHAR(30)
);