CREATE TABLE USERS (
  RPI_ID VARCHAR(10) NOT NULL, --User
  ACTIVE_LISTINGS VARCHAR(5000) NOT NULL, --FIGURE OUT WHY SIZE IS LIMITING ME
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  PAST_LISTINGS VARCHAR(5000) NOT NULL, --FIGURE OUT WHY SIZE IS LIMITING ME
  USER_PASSWORD VARCHAR(8) NOT NULL,
  USER_LOCATION VARCHAR(30) NOT NULL
);